/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  LoginComponent as LoginComponent
} from './components/login-component/login-component';

declare global {
  interface HTMLLoginComponentElement extends LoginComponent, HTMLStencilElement {
  }
  var HTMLLoginComponentElement: {
    prototype: HTMLLoginComponentElement;
    new (): HTMLLoginComponentElement;
  };
  interface HTMLElementTagNameMap {
    "login-component": HTMLLoginComponentElement;
  }
  interface ElementTagNameMap {
    "login-component": HTMLLoginComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "login-component": JSXElements.LoginComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface LoginComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
